### ISSUE TITLE
Decompose LabVIEW Object fails with private data control set to indicator

### ISSUE THREAD

**Issue by LogMANOriginal** [LogMANOriginal/LabVIEW-Composition#9]
Originally reported in #8 
Changing the private data control to indicator breaks **Decompose LabVIEW Object**.

![image](https://user-images.githubusercontent.com/5776685/120855415-b6e5d980-c57e-11eb-9cba-0f5920d6cc4f.png)

**Comment by justiceb** [comment]
This bug makes me laugh.  Only in LabVIEW
